### PR TITLE
Added a alert dialog when trying to delete a debt/credit.

### PR DESCRIPTION
**Pull request by Spyy004**
I have added an alert dialog. It pops up whenever a user tries to delete a debt/credit. I have also added localizations for french and English accordingly.

Please provide feedback if any and merge the code if you find the changes helpful and correct.

### CODE REVIEW

**Comment by h4h13** [comment]
Can you remove the dialog part I have added that already but IDK why you have not seen, and you can create a PR for translation and please and latest update and check if anything new translations added

**Comment by Spyy004** [comment]
there wasn't a dialog box when you try to delete a debt or a credit when i used the app. So i added it just on that page. There was a dialog box when you try to delete a category but not at debt/credit deletion

**Comment by Spyy004** [comment]
and  please and latest update and check if anything new translations added

Also, didn't understood this part...

**Comment by h4h13** [comment]
> there wasn't a dialog box when you try to delete a debt or a credit when i used the app. So i added it just on that page. There was a dialog box when you try to delete a category but not at debt/credit deletion

Interesting are working on latest code ? or can you show video or image

**Comment by h4h13** [comment]
> and please and latest update and check if anything new translations added
> 
> Also, didn't understood this part...

you have added localizations for french, I have added new strings that you consider tranlsate  also

**Comment by Spyy004** [comment]
well, yeah i forked the repo and started working so it was the master branch. Master is the latest right?

**Comment by Spyy004** [comment]
https://user-images.githubusercontent.com/54628130/227724398-a4d2be33-2bf8-4e33-be7a-6098363a3455.mp4

This is the dialog box that I have added. Is this already present?

**Comment by Spyy004** [comment]
any updates brother ?

**Comment by h4h13** [comment]
Got it

**Pull request merged**
