### PR TITLE
Improve add expense screen

### PR DESCRIPTION
**Pull request by Lenart12**
This PR implements the following:
* Sort account and category by time of last use, not by name
* Change page title dynamicly depending if transaction is expense or income
* Remove Add new buttons, this can be done in their specific pages and reduces clutter for quick operations

### CODE REVIEW

**Comment by h4h13** [comment]
Hey Sorry didn't you're working on expense page can you check the conflicts and feature I have added recently

**Comment by Lenart12** [comment]
Fixed merge conflicts

**Comment by h4h13** [comment]
What is the flutter version your using, does it crashing when add or editing the expense

**Comment by h4h13** [comment]
But we need add expense and category

**Comment by Lenart12** [comment]
> What is the flutter version your using, does it crashing when add or editing the expense

It does not crash.
```
flutter --version
Flutter 3.7.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 90c64ed42b (7 days ago) • 2023-03-21 11:27:08 -0500
Engine • revision 9aa7816315
Tools • Dart 2.19.5 • DevTools 2.20.1
```

> Looks like code you can improve by using use-case rather than using bloc invoking.

Code works fine, so I dont see the need to change it.

> But we need add expense and category

Once the user sets up his categories, he will rarely add new categories, so why make it such a big element that is not needed most of the time. It is better to add a quick shortcut to the full page manager (like it was removed from previous versions), because is there only the option to add new but not to edit or delete. If you do not like the removal of this button, can it be a setting that the user can choose to hide it.

**Comment by h4h13** [comment]
Latest flutter version crashing for me so I downgraded and downgraded some libs also

**Pull request closed without merging**
