### PR TITLE
Allows setting a font preference.

### PR DESCRIPTION
**Pull request by aaorszulak**
This fixes the #156 by allowing the user to choose preferred font.

This would be my first draft. Please tell me if this is something you would be comfortable merging, or if there are any change you would like to see.

Screenshot 2023-03-27 at 00 06 36

I took the liberty of selecting few fonts to choose from. It is possible to add more, or event allow the user to choose from the whole google fonts catalog, but the list is very very long.

### CODE REVIEW

**Comment by h4h13** [comment]
Hey, Thanks for the PR, let me test and get back with feedback

**Comment by h4h13** [comment]
image
Fonts are not supporting in dart mood and a good start

**Comment by aaorszulak** [comment]
I will fix this when I'm back from vacation. Next week.

**Comment by h4h13** [comment]
For fonts you can query all fonts and show

**Comment by aaorszulak** [comment]
I fixed the issue with dark theme, and allowed the user to choose from all available fonts.

**Comment by h4h13** [comment]
Did you added Default and all the google fonts list to work ?

**Comment by h4h13** [comment]
Can you make that each font preview like before so that user knows how to font looks like

**Comment by aaorszulak** [comment]
Yes, I can re-enable this.

**Comment by h4h13** [comment]
image
I have changed font, check this some places we're still using the hard coded kinda font because of fontweight check this

**Comment by aaorszulak** [comment]
I changed every instance of outfit to the chosen font and re-enabled font preview.

**Comment by h4h13** [comment]
This is good to have feature have created branch for it as when I tried it's difficult for me too see other fonts in-app closing it for now

**Comment by h4h13** [comment]
Thank you very much for initiation

**Pull request closed without merging**
